apiVersion: v1
kind: Service
metadata:
  name:  mysql-h
spec:
  selector: #aqui vamos filtrar os POD's, que estão neste serviço
    app: mysql #pega todos os POD's (nesse vai no deployment) que são goserver
  ports:
    - port: 3306 #porta do service     
  clusterIP: None
