apiVersion: v1
kind: Service
metadata:
  name:  mysql-h # mame of service ( Headless Service )
spec:
  #selector: selector all POD's with name mysql
  selector: 
    #app: select POD's with name mysql 
    app: mysql 
  ports:
    #port: port of service
    - port: 3306   
  clusterIP: None #only point to DNS
