apiVersion: apps/v1
kind: StatefulSet  #type of manifest/resource
metadata:
  name: mysql  #name of statefulset
  labels:
    app: mysql #label of satefulset
spec:
  selector:
    matchLabels:
      app: mysql #name of Pod
  serviceName: mysql-h #name of service
  #podManagementPolicy: Parallel ##creating a Pod parallel to our StatefulSet
  replicas: 3 #number of replicas
  template: #temaplate of POD
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-volume

  volumeClaimTemplates:
  - metadata:
      name: mysql-volume #name of persistent volume
    spec:
      accessModes:
        - ReadWriteOnce #type access
      resources:
        requests:
          storage: 1Gi #disk reserved space
            
    
