apiVersion: apps/v1
kind: StatefulSet  # type of manifest/resource
metadata:
  name: mysql  # name of statefulset
  labels:
    app: mysql # label fo satefulset
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql-h #
  #podManagementPolicy: Parallel #criação de Pod forma parelela do nosso StatefulSet
  replicas: 3
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-volume

  volumeClaimTemplates:
  - metadata:
      name: mysql-volume
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
            
    
