apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler # type of manifest/resource
metadata:
  #name: name of hpa
  name: goserver-hpa
spec:
 scaleTargetRef:
   apiVersion: apps/v1 #api of the deployment version we are scaling
   name: goserver # name application
   kind: Deployment # type of application
 minReplicas: 1 #minimum number of replicas that we wuil start the application
 maxReplicas: 5 #maximum number of replicas we will have
 targetCPUUtilizationPercentage: 50 #metric that will look to scale the pods
        
